export default {
  bg: require('../assets/images/bg.png'),
  bg1:require('../assets/images/bg1.png'),
  bg2:require('../assets/images/bg2.png'),
  emptyOrder:require('../assets/images/emptyorder.png'),
  person:require('../assets/images/person.png'),
  person1:require('../assets/images/person1.png'),
  profile:require('../assets/images/profile.png'),
  submit:require('../assets/images/submit.png'),
  partners:require("../assets/images/partners.png"),
  successGif: require("../assets/images/success.gif"),
  plateImg: require("../assets/images/plate.png"),
  hungerLogo: require("../assets/images/hunger_bites_logo.png"),
  bellIcon: require("../assets/images/bell_active.png"),
  foodBanner: require("../assets/images/Fast_Food_Modern_Banner_Landscape.png"),
  foodBanner2: require("../assets/images/Green_and_White_Modern_Vegan_Food_Banner.png"),
  foodBanner3: require("../assets/images/Orange_and_Black_Simple_Food_Banner.png"),
  foodBanner4: require("../assets/images/White_and_Black_Minimalist_Healthy_Food_Banner_Landscape.png"),
}